trigger:
- main

pool:
  name: 'Default'

variables:
  dockerRegistryServiceConnection: 'dmytroleksiienko-acr'
  imageRepository: 'dmytrooleksiienkolab6oleksiienko'
  containerRegistry: 'dmytroleksiienko.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/complete/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build Job
    steps:
    # 1. Компіляція коду прямо всередині пайплайну
    - task: Maven@4
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'complete/pom.xml'
        goals: 'package -DskipTests'
        options: '-Dmkdir target/dependency && (cd target/dependency; jar -xf ../*.jar)'
        publishJumpTestResults: false

    # 2. Збірка Docker-образу (тепер target/ точно буде на місці)
    - task: Docker@2
      displayName: "Build Image for AMD64"
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        arguments: '--platform linux/amd64'
        tags: |
          $(tag)

    # 3. Пуш в Azure ACR
    - task: Docker@2
      displayName: "Push Image to ACR"
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)