trigger:
- main

pool:
  name: 'Default'

variables:
  dockerRegistryServiceConnection: 'dmytroleksiienko-acr'
  imageRepository: 'dmytrooleksiienkolab6oleksiienko'
  containerRegistry: 'dmytroleksiienko.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/complete/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build Job
    steps:
    - checkout: self

    # 1. Збірка проєкту та підготовка структури target/dependency
    - script: |
        cd complete
        chmod +x mvnw
        ./mvnw package -DskipTests
        # Створюємо папку, яку шукає твій Dockerfile (ARG DEPENDENCY=target/dependency)
        mkdir -p target/dependency
        # Розпаковуємо JAR-файл у цю папку
        cd target/dependency
        jar -xf ../*.jar
      displayName: 'Maven Package and Unpack'

    # 2. Збірка Docker-образу (під архітектуру x86_64 для Azure)
    - task: Docker@2
      displayName: "Build Docker Image"
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        buildContext: '$(Build.SourcesDirectory)/complete'
        arguments: '--platform linux/amd64'
        tags: |
          $(tag)

    # 3. Пуш образу в ACR
    - task: Docker@2
      displayName: "Push Image to ACR"
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)